changeLogFile=sources/facilities/master.xml

#for docker use
liquibase.command.url=jdbc:oracle:thin:@//oracle-facilities:1521/facilities
#for local use
#liquibase.command.url=jdbc:oracle:thin:@//localhost:1521/facilities
liquibase.command.username=liquibase
liquibase.command.password=entornodev
